-- First, remove the table if it exists
drop table if exists bookmark_data;

-- Create the table anew
create table bookmark_data (
  id INTEGER primary key generated by default as identity,
  bookmark_title text,
  bookmark_url VARCHAR(60),
  rating int, 
  bookmark_description text
);

-- insert some test data
-- Using a multi-row insert statement here
insert into bookmark_data (bookmark_title, bookmark_url, rating, bookmark_description)
values
  ('Google', 'https://www.google.com/', '5', 'Worlds number one search engine'),
  ('Thinkful', 'https://www.thinkful.com/', '4', 'Learn to code and stuff'),
  ('C-Span', 'https://www.c-span.org/', '3', 'Your unfiltered view of government'),
  ('Youtube', 'https://www.youtube.com/', '4', 'Demonetize everyone!'),
  ('Facebook', 'https://www.facebook.com/', '1', 'This site gave me covid19'),
  ('Blizzard', 'https://www.blizzard.com/en-us/', '3', 'Your dad is a gnome'),
  ('Amazon', 'https://www.amazon.com', '2', 'Bezos owns you'),
  ('Repl.it', 'https://repl.it/', '3', 'Learn to code here'),
  ('Github', 'https://github.com/', '5', 'A place for all your repo needs'),
  ('Bethesda', 'https://bethesda.net/en/dashboard', '1', 'All yore Bethesda are belong to us');